language: python
python:
- "3.6"
env:
- DJANGO=2.0 DB=postgres
before_install:
- cd decide
install:
- pip3 install -r ../requirements.txt
script:
- cd mixnet
- python3 zkp.py
- cd ..
services:
  - postgresql
addons:
  postgresql: "10"
global:
  - PGPORT=5432
before_script:
 - cd .. cp local_settings.travis.py local_settings.py
 - cd decide
 - psql -c "create user decide with password 'decide'"
 - psql -c "create database decide owner decide"
 - python3 manage.py migrate
 - cd mixnet
 - python3 zkp.py
 - cd ..
